### ISSUE TITLE
How to change timer from 300s to 90s?

### ISSUE THREAD

**Issue by L1neHypeR** [whirlfrenzy/item-despawn-timer#1]
Hello! How to change timer from 300s to 90s?

**Comment by whirlfrenzy** [comment]
This mod itself doesn't change the item despawn duration, it just tells you when it does
Although it does that by assuming that every item despawns within 300s, which is an issue when you have a seperate mod that changes the despawn duration
I haven't added any kind of config so far, but it's planned for the future

**Comment by whirlfrenzy** [comment]
> Hello! How to change timer from 300s to 90s?

Just finished a new mod that lets you change the despawn time for items
You can download it here: https://github.com/whirlfrenzy/custom-item-despawn-duration/releases
Modrinth and CurseForge are still reviewing it tho
