### ISSUE TITLE
This mod caused our server to crash

### ISSUE THREAD

**Issue by MarkHarrisMedia** [whirlfrenzy/item-despawn-timer#3]
The numbers get stuck and won’t disappear, this caused repeating errors on server console. Be warned, this WILL break your server. I had to restore from a previous backup and lost recent work we did…. Not happy

**Comment by whirlfrenzy** [comment]
Could you provide logs and mods used? The mod shouldn't be able to break servers as it only retrieves an item entity's item age and sends them to the clients. Could likely be a mod incompatibility issue

**Comment by whirlfrenzy** [comment]
Closing this as no logs nor a list of mods used was provided
