### ISSUE TITLE
[Suggestion] Hide timer text until it reaches a specific number?

### ISSUE THREAD

**Issue by Cixon** [whirlfrenzy/item-despawn-timer#6]
I noticed it applies as soon as a item drops but what if you could scale it to display at a specific time? For example, the display activates for items at or below 60 seconds.

**Comment by Cixon** [comment]
I would imagine some may not like this feature so a optional way to configure it via config would be nice. I use 1.21.1 NeoForge version btw. Great mod!

**Comment by whirlfrenzy** [comment]
Has been added with v0.2.1 with the timer visibility threshold config, which is now on Modrinth (and pending review on CurseForge)
Thanks for the suggestion
